export const VENDORS = [
  "Microsoft",
  "Salesforce",
  "SAP",
  "Oracle",
  "ServiceNow",
  "Workday",
  "Adobe",
  "IBM",
  "Google Cloud",
  "AWS",
  "Snowflake",
  "Databricks",
  "Atlassian",
  "Zoom",
  "Slack (Salesforce)",
  "HubSpot",
  "Zendesk",
  "Palo Alto Networks",
  "CrowdStrike",
  "Splunk",
  "VMware (Broadcom)",
  "Citrix",
  "DocuSign",
  "Okta",
  "Twilio",
  "Stripe",
  "Shopify",
  "Intuit",
  "Coupa",
  "UiPath",
] as const;

export const INDUSTRIES = [
  "Financial Services & Banking",
  "Healthcare & Life Sciences",
  "Technology & Software",
  "Manufacturing & Industrial",
  "Retail & E-Commerce",
  "Energy & Utilities",
  "Telecommunications",
  "Government & Public Sector",
  "Education & Research",
  "Media & Entertainment",
  "Professional Services & Consulting",
  "Transportation & Logistics",
  "Real Estate & Construction",
  "Insurance",
  "Nonprofit & NGO",
] as const;
